mod island_stories_base;
mod the_just_walking_event;
mod the_hidden_cove_treasure_event;
mod the_mysterious_shipwreck_event;
mod the_tropical_fruit_grove_event;
mod the_ancient_temple_ruins_event;
mod the_stranded_sailor_event;
mod the_mysterious_fog_bank_event;
mod the_abandoned_pirate_outpost_event;
mod the_mysterious_idol_event;
mod the_lost_city_of_gold_event;
mod the_krakens_treasure_event;
mod the_bermuda_triangle_anomaly_event;
mod the_fountain_of_youth_event;
mod the_ghost_ships_challenge_event;
mod the_pirate_kings_tomb_event;
mod the_mermaids_grotto_event;
mod the_krakens_awakening_event;
mod the_time_storm_event;
mod the_celestial_island_event;
mod the_void_maelstrom_event;
mod the_pirates_carnival_event;
mod the_pirates_regatta_event;
mod the_awakening_of_the_kraken_god_event;

pub use island_stories_base::*;
pub use the_just_walking_event::*;
pub use the_hidden_cove_treasure_event::*;
pub use the_mysterious_shipwreck_event::*;
pub use the_tropical_fruit_grove_event::*;
pub use the_ancient_temple_ruins_event::*;
pub use the_stranded_sailor_event::*;
pub use the_mysterious_fog_bank_event::*;
pub use the_abandoned_pirate_outpost_event::*;
pub use the_mysterious_idol_event::*;
pub use the_lost_city_of_gold_event::*;
pub use the_krakens_treasure_event::*;
pub use the_bermuda_triangle_anomaly_event::*;
pub use the_fountain_of_youth_event::*;
pub use the_ghost_ships_challenge_event::*;
pub use the_pirate_kings_tomb_event::*;
pub use the_mermaids_grotto_event::*;
pub use the_krakens_awakening_event::*;
pub use the_time_storm_event::*;
pub use the_celestial_island_event::*;
pub use the_void_maelstrom_event::*;
pub use the_pirates_carnival_event::*;
pub use the_pirates_regatta_event::*;
pub use the_awakening_of_the_kraken_god_event::*;